require_relative 'support/knife_solo_provisioner'

Vagrant::Config.run do |config|
  config.vm.define :ubuntu12 do |c|
    c.vm.box       = "opscode-ubuntu-12.04"
    c.vm.box_url   = "https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box"
    c.vm.network :hostonly, "10.0.3.4"
    c.vm.provision KnifeSoloProvisioner do |p|
      p.knife_path  = File.expand_path('../../../b/knife', __FILE__)
      p.node_config = "ubuntu12.json"
      p.options     = "-VV"
    end
  end
end
