#!/bin/sh

set -e

help() {
  echo
  echo === Thanks for helping with Knife-Solo! ===
  echo
  echo The b folder contains bundler bin-stubs. These will let you test your changes more easily.
  echo
  echo Just run:  $(cd `dirname $0`/.. && pwd )/b/knife
  echo
  echo If you want to run integration testing grab your AWS keys from https://aws-portal.amazon.com/gp/aws/securityCredentials and enter them in test/support/config.yml
  echo
  echo Then generate a keypair called knife-solo at 'https://console.aws.amazon.com/ec2/home?region=us-east-1&#s=KeyPairs' and place this key in test/support/knife-solo.pem
}

setup() {
  gem install bundler
  bundle --binstubs=b
  rake
  if [[ ! -e test/support/config.yml ]]; then
    cp test/support/config.yml{.example,}
  fi
}

case $1 in
  help)
    help
    ;;
  *)
    setup
    help
    ;;
esac
