name             'cache_using_cookbook'
maintainer       'Mat Schaffer'
maintainer_email 'mat@schaffer.me'
license          'MIT'
description      'Writes some data to the cache path.'
long_description 'This helps ensure that we can do this multiple times regardless of what user initiates the run.'
version          '0.1.0'
